### ISSUE TITLE
Undefined method "attachments" for instance of model

### ISSUE THREAD

**Issue by aaaknowit** [igorkasyanchuk/active_storage_validations#287]
After updating to 1.3.2 I can no longer access my model instance's "attachments" relation. Fixed it by downgrading to 1.3.0

**Comment by Mth0158** [comment]
> After updating to 1.3.2 I can no longer access my model instance's "attachments" relation. Fixed it by downgrading to 1.3.0

Hi @aaaknowit,
Did you upgrade from 1.3.1 to 1.3.2 or straight from 1.3.0 to 1.3.2?
Plus, I need more context to be able to solve the bug, can you give us your attachment process + model configuration?

**Comment by cernyjakub** [comment]
I have has_many associations defined in a model via concern. After upgrading to 1.3.1, these became unavailable. Upgrading to 1.3.2 did not help unfortunately.

```
class Article < ApplicationRecord
  include Attachable
end

module Attachable
  extend ActiveSupport::Concern
  included do
    has_many :photos, :as => :attachable, :dependent => :destroy
  end
end
```

Error: NameError - undefined local variable or method `photos' for #<Article id: ...

**Comment by aaaknowit** [comment]
Direct from 1.3.0. 

I have a mixin (concern) Attachable that is mixed in in a super-superclass of my model. Configured like this

```ruby
  included do
    has_many :attachments, as: :attachable, dependent: :destroy
  end
```

Class A includes this; Class B < A; Class C < B and C's instances cannot find any local variable "attachments".

**Comment by Mth0158** [comment]
I thought I fixed this issue, I will work on a fix today so the gem works fine when the app defines a concern that has the same name as one of the concern used in our app.

**Comment by Mth0158** [comment]
Hi everyone,
It should now work fine with 1.3.3 when the fix is released (in the coming hours). Let me know if there are other issues arising or if you would like new features to this gem ;)

**Comment by Mth0158** [comment]
The issue is now solved as the 1.3.3 release has been done :)
Let me know if there are still some issues (I hope not 😅, the bugs weren't expected, but at least with have test coverage for later changes)
